# Usar imagen base de Python 3.12
FROM python:3.12-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo Python al contenedor
COPY numeroaleatorio.py /app/

# Ejecutar el script Python
CMD ["python", "numeroaleatorio.py"]
