# Usar una imagen base de Python 3.12
FROM python:3.12-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo Python correcto al contenedor
COPY numeroaleatorio.py /app/

# Ejecutar el script de Python
CMD ["python", "numeroaleatorio.py"]
