# Usamos la imagen base de Python 3.12
FROM python:3.12-slim

# Establecemos el directorio de trabajo en el contenedor
WORKDIR /app

# Copiamos el archivo app.py al contenedor
COPY app.py .

# Ejecutamos el script cuando se inicie el contenedor
CMD ["python", "app.py"]
